project:
  type: website
  output-dir: docs

website:
  title: "BIO 123 Notes"
  sidebar:
    style: "docked"
    contents:
      - section: "Part 1: Science of Life"
        contents:
          - chapters/Chapter-5.qmd
          - chapters/Chapter-6-key-concept.qmd
          - chapters/Chapter-7.qmd
          - chapters/Chapter-8.qmd

format:
  html:
    css: style.css