---
title: "Chapter 5 Cells: The Working Units of Life"
format: html
toc: true
---

## 5.1 Cells Are the Fundamental Units of Life

- [Cell theory]{.underline}:

  1.  Cells are the fundamental units of life.
  2.  All living organisms are composed of cells.
  3.  All cells come from preexisting cells.
  4.  Modern cells evolved from a common ancestor.

- 3 important implications of cell theory:

  1.  Studying cell biology is in some sense the same as studying life.
  2.  Life is continuous.
  3.  The origin of life on Earth was marked by the origin of the first cells.

- several important roles of [membrane]{.underline}:

  - acts as a selectively permeable barrier:

    - prevent some substances from crossing in

    - permit other substances to enter & leave the cell

  - regulate transport across it $\Rightarrow$ allows the cell to maintain a more or less constant internal environment

  - important in

    - communicating with adjacent cells

    - receiving signals from the environment

- Everything inside the cell, except for the nucleus if the cell has one, is termed the [cytoplasm]{.underline}.

- The cytosol is the fluid cytoplasm not contained inside another compartment.

- [prokaryote]{.underline}: organisms in Archaea and Bacteria

  - does not have membrane-enclosed internal compartments
  - does not have a nucleus

- [eukaryote]{.underline}: protists 原生生物, plants, fungi, and animals

  - contain membrane-enclosed comaprtments called [organelles]{.underline}

- [nucleus]{.underline}:

  - where most of the cell's DNA is located

  - where gene expression begins

## 5.2 Prokaryotic Cells Are the Simplest Cells

- [nucleoid]{.underline} \[病毒\] 病毒核心; \[细胞\] 类核: region in the cell where the DNA is located

- ribosomes 核糖体: complexes of RNA and proteins in the cytoplasm

- cell wall

  - located outside the cell membrane

  - supports the cell

  - determines cells' shape

- cell wall of most bacteria, but not archaea:

  - contain **peptidoglycan**: a polymer of amino sugars that is linked at regular intervals to short peptides

- in some bacteria, **outer membrane**: polysaccharide-rich phospholipid membrane

  - encloses the peptidoglycan layer

- in some bacteria. **capsule**: a slimy layer composed mostly of polysaccharides

  - enclosing the cell wall

- some bacteria have an **internal membrane system**: contains molecules needed for photosynthesis

- some prokaryotes swim by using appendages called **flagella**

  - sometimes look like tiny corkscrews

- **pill**: structures made of protein

  - project from the surfaces of some types of bacterial cells

- **cytoskeleton**: protein filaments

  - play roles in cell division, cell movement, and in maintaining the shapes of cells.

## 5.3 Eukaryotic Cells Contain Organelles

- **nucleus**:

  - location of most of the cell's DNA and the site of DNA replication

  - the site where gene transcription is turned on or off

  - **nucleolus**: a region within the nucleus

    - where ribosomes begin to be assembled from RNA and proteins

- the nucleus is enclosed by **nuclear envelope**: an integrated structure composed of two membranes

- chromosomes: long, thin threads

  - made up by chromatin: inside nucleus, DNA molecule + proteins

- **endomembrane system**: interconnected system of membrane-enclosed compartments, includes:

  - cell membrane

  - nuclear envelope

  - endoplasmic reticulum 内质网

  - Golgi apparatus \[细胞\] 高尔基氏体; 内网器

  - lysosomes 溶酶体

- **vesicles** 囊: membrane-surrounded droplets

  - shuttle substances between the various components of the endomembrane system

- **endoplasmic reticulum** (ER) 内质网: networks of interconnected membranes branching throughout the cytoplasm

  - forming tubes and flattened sacs

- **rough endoplasmic reticulum** (RER) 带有核糖体的内质网: many ribosomes attached to the outer surface of the membrane, giving it a "rough" appearance in electron microscopy

  - receives into its **lumen** 内腔 (管状器官内的空腔) certain newly synthesized proteins

    - segregating them away from the cytoplasm

    - participates in transporting these proteins to other locations in the cell

  - proteins can be

    - chemically modified to alter their functions

    - "tag" them for delivery to specific cellular destinations

  - proteins are sent to destinations elsewhere in the cell enclosed within vesicles that pinch off from the RER

  - most membrane-bound proteins are made in the RER

  - **glycoproteins** 糖蛋白: some proteins become covalently linked to carbohydrate groups in the RER

- **smooth endoplasmic reticulum** (SER) 平滑内质网: lacks ribosomes and is more tubular (and less like fattened sacs) than the RER, but shows continuity with portions of the RER

  - responsible for the chemical modification of small molecules taken in by the cell that may be toxic to the cell

    - make the targeted molecules more polar, so they are more water soluble and easily removed

  - is the site for glycogen degradation in animal cells

  - where lipids and steroids are synthesized, as well as some polysaccharides 多糖 in plant cells

  - store calcium ions, released trigger numerous cell responses

- **Golgi apparatus** 内网器, consists of two components: flattened membranous sacs called **cisternae** 潴泡 (singular cisterna) that are piled up like saucers, and small membrane-enclosed vesicles

  - receives protein-containing vesicles from the RER

  - modifies, concentrates, packages, and sorts proteins. before they are sent to their cellular or extracellular destinations

  - adds carbohydrates to proteins

  - modifies other carbohydrates that were attached to proteins in the RER

  - where some polysaccharides for the plant cell wall are synthesized

  - cuts certain large precursor proteins transferred from the RER into smaller, functional fragments

- 3 functionally distinct regions (faces) of Golgi apparatus:

  1.  The *cis* face lies nearest to the nucleus or a patch of RER
  2.  The *trans* face lies closest to the cell membrane
  3.  The *medial* face lies in between

- primary lysosomes: originate from the Golgi apoparatus

- contain digestive enzymes

- the sites where **macromolecule**s (protein, polysaccharides, nucleic acids, lipids) are hydrolyzed into their monomers

- **phagocytosis** 吞噬作用: a process of food, other cells, or foreign objects enter the cell

- **secondary lysosome** \[细胞\]\[免疫\] 次级溶酶体: phagosome 吞噬体 fuses with a primary lysosome to form a \~

  - where digestion occurs

  - there reactions are enhanced by the acidity of the lysosome's interior

- **exocytosis** (细胞生物学) 胞吐作用:

  - the "used" secondary lysosome containing undigested particles

  - moves to the cell membrane

  - fuses with it, and releases the undigested contents to the environment

- **autophagy** (生物学) 自噬: programmed destruction of cell components

  - some cell components are continually being broken down and replaced by new ones

- **lysosomes** 溶酶体:

  - where the cell breaks down its own materials

  - with the proper signal, lysosomes can engulf entire organelles, hydrolyzing their constituents

- **lysosomal storage diseases**: caused by the failure of lysosomes to digest specific cellular components

  - invariably harmful or fatal

  - e.g. **Tay-Sachs disease** 黑蒙性家族性痴愚; 泰-萨二氏病

    - a particular lipid called a **ganglioside** \[生化\] 神经节苷脂 is not broken down in the lysosomes

    - instead accumulates in brain cells

    - a baby starts exhibiting neurological symptoms and becomes blind, deaf, and unable to swallow after 6 months of age

    - death occurs before age 4

- plant cells do not appear to contain lysosomes, but the **vacuole** \[细胞\] 液泡 of a plant cell may function in an equivalent capacity because it, like lysosomes, hydrolyzes macromolecules

- energy is harvested from

  - fuel molecules in the **mitochondria** 线粒体 (**mitochondrion** 的复数)

    - found in all eukaryotic cells

  - sunlight in the **chloroplast**s 叶绿体 of plant cells\\

- energy in biological systems is stored and transferred in the form of [covalent bonds]{.underline} in organic molecules

- In eukaryotic cells, breakdown of energy-rich molecules sucha s glucose begins in the cytoplasm.

- mitochondria:

  - harvests the chemical-bond energy of those molecules in a form that he cell can use

  - namely the [energy-rich molecule]{.underline} ATP (**adenosine triphosphate** 腺苷三磷酸)

  - some can reproduce and divide independently of the central nucleus

  - Cells that are [active in movement and growth]{.underline} require the [most chemical-bond energy]{.underline} and tend to have the [most mitochondria]{.underline}.

- cellular respiration

  - production of ATP in the mitochondria

  - using fuel molecules and molecular oxygen ($\ce{O2}$)

- Mitochondria have [two membranes]{.underline}:

  - **outer membrane**:

    - smooth

    - permits the movement of substances into and out of the organelle

  - **inner membrane**:

    - folds inward in many places

    - has a surface area much greater tha nthat of the outer membrane

    - **cristae** 脊: shelflike structures

    - exerts much more control over what enters and leaves the space it encloses than does the outer membrane

  - large protein complexes embedded in the inner mitochondrial membrane

    - participate tin cellular respiration

- **mitochondrial matrix** 线粒体基质

  - the space enclosed by the inner membrane

  - contains [ribosomes and DNA]{.underline} that are used to make some of the mitochondrial proteins needed for cellular respiration

- **plastid**s 质体，色素体:

  - occur only in the cells of plants and certain protists

  - can divide independently of the cell nucleus

- **chloroplast**s 叶绿体: $\nwarrow$ (one type of plastids)

  - contain the green pigment **chlorophyll** 叶绿素

  - are the sites of **photosynthesis**

    - light energy is converted into chemical-bond energy

  - enclosed by two membranes

  - **thylakoid**s 类囊体: a series of internal membrane that often look like stacks of flat, hollow pita bread

    - only 10% are **phospholipid**s 磷脂

    - the rest are **galactose-substituted diglyceride**s 半乳糖取代的二甘油酯 and **sulfolipid**s 硫脂

    - are the most abundant lipids in the biosphere

    - the membranes of the thylakoids contain chlorophyll and other pigments taht harvest light energy for photosynthesis

  - The thylakoids of one granum may be [connected to those of other grana]{.underline}, making the interior of the chloroplast [a highly developed network]{.underline}, much like the ER.

  - **stroma** 间质: the [fluid]{.underline} in which the grana are suspended

    - contains [ribosomes nad DNA]{.underline}

      - used to synthasize some chloroplast polypeptides

- **chromoplast** 色素母细胞 (another type of plastids)

  - [make and store red, yellow, and orange pigments]{.underline}

  - especially in [flowers and fruits]{.underline}

- **leucoplast**s \[植\] 白色体 (another type of plastids):

  - storage organelles that [store starch]{.underline}

- 3 other organelles whose [boundary membranes separate their specialized chemical reactions and contents]{.underline} from the rest fo the cytoplasm: **peroxisome**s 过氧物酶体, **glyoxysome**s 糖体, and **vacuole**s 液泡.

- **peroxisome** 过氧物酶体:

  - found only in plants

  - organelles that accumulate toxic peroxides

    - e.g. hydrogen peroxide ($\ce{H2O2}$): occur as byproducts of some biochemical reactions

    - safely broken down inside the peroxisomes without mixing with other parts of the cell

    - $$\ce{RH2 + O2 -> R + H2O2 \text{(cellular reactions)}} \\
      \ce{2H2O2 -> 2H2O + O2 \text{(inside peroxisome)}}$$

- **glyoxysome** 糖体:

  - found only in plants

  - most abundant in young plants

  - they are the locations where stored lipids are converted into carbohydrates for transport to growing cells

  - The direct conversion of fat to carbohydrate is unique to these plants.

- **vacuole** 液泡:

  - occur in many eukaryotic cells but particularly those of plants, fungi, and protists

  - arise from the ER or Golgi apparatus

  - structure:

    - in many plant cells, \~ take up more than 90% of the cell volume

    - grow as the cell grows

    - presence of dissolved substances in the vacuole [causes water to enter it]{.underline} from the cytosol, making the vacuole [swell like a balloon]{.underline}

    - A [mature]{.underline} plant cell does not swell when the vacuole fills with water, since it has a rigid cell wall.

    - Instead, it stiffens 绷紧 from the increase in water pressure (called **turgor** (细胞组织的) 肿胀), and this supports the plant body.

  - reproduction:

    - \~ contains some fo the pigments (especially blue and pink) in the petals and fruits of flowering plants

    - these pigments – the **anthocyanin**s 花色素苷 – are [visual cues]{.underline} that help attract animals that assist in [pollination]{.underline} or [seed dispersal]{.underline}

  - digestion:

    - in some plants, \~ in seeds contain molecules that hydrolyze [stored proteins]{.underline} into [monomers]{.underline}

    - during [seed germination]{.underline} 发芽, the monomers are used as [food]{.underline} by the developing plant seedlings

  - storage:

    - storing water

    - store toxic molecules and waste products

    - they may be poisonous or distasteful, these stored materials deter some animals from eating the plants and contribute to [plant defense and survival]{.underline}

    - e.g. **tannin**s 单宁酸: a class of **polyphenol**s 多元酚 (具有抗氧化作用), made in many plants; in [tea and red wine]{.underline}

      - bitter taste deters predators

      - dark color acts like animal melanin 黑色素 to protect the plant from ultraviolet light dmg

      - made in the chloroplast and end up in the vacuole

      - A newly disc9overed organelle, named tannosome 单宁体, contains tannins.

- **cytoskeleton** 细胞骨架:

  - supports the cell and maintains its shape

  - holds cell organelles and other particles in position within the cell

  - moves organelles and other particles around in the cell

  - involved with movements of the cytoplasm, called **cytoplasmic streaming** 细胞质流动

  - interacts with extracellular structures, helping anchor 锚 the cell in place

- **microfilament**s 微丝:

  - can exist as single filaments, in bundles, or in networks

  - about $\pu{7nm}$ in diameter and up to several micrometers long

  - two major roles:

    1.  helpo the entire cell or parts of the cell move
    2.  determine and stabilize cell shape

  - assembled from monomers of **actin** 肌动蛋白: a protein that exists in several forms; has many function, especially in animals

    - has distinct ends: designated "plus" and "minus"

    - these ends permit actin monomers to interact with one another to form long, double-helical chains

    - the polymerization of actin into microfilaments is reversible

    - the microfilaments can disappear from cells by breaking down into monomers of free actin

    - Special actin-binding proteins mediate these processes.

    - in non-muscle cells, \~ filaments are associated with localized changes in cell shape

      - e.g. cytoplasmic streaming: flowing movement of the cytoplasm

      - e.g. amoeboid movement \[细胞\] 变形运动

      - e.g. "pinching" contractions that divide an animal cell into two daughter cells

    - involved in the formation of cellular extensions called **pseudopodia** 伪足: enables some cells to move

- **intermediate filament**s 中间纤维

  - at least 50 different kinds

  - generally fall into six molecular classes that share the same general structure

  - one of these classes consists of fibrous proteins fo the [keratin family]{.underline}, which also includes the proteins that make up hair and fingernails

  - tough, ropelike protein structures $\pu{8-12nm}$ in diametere

  - more permanet tthatn the other two types in that they do not continually form and re-form

  - two major structural functions:

    1.  anchor cell structures in place
        - radiate from the nuclear envelope and help maintain the position of the nucleus and other organelles in the cell
    2.  resist tension
        - maintian rigidity in body surface tissues by stretching through the cytoplasm

        - connecting specialized membrane structures called desmosomes 细胞桥粒 (上皮细胞膜中的局部增厚部份)

- **microtubules** 微管: long, hollow, unbranched cylinders about $\pu{25nm}$ in diameter and up to several micrometers long

  - two roles in the cell:

    1.  form a rigid internal skeleton for some cells
    2.  act as a framework along which motor proteins can move structures within the cell

  - Microtubule = chain of dimers

  - **dimer** 二聚物 = $\alpha$-tubulin 微管蛋白 + $\beta$-tubulin (paired)

  - $\alpha$ and $\beta$ = two similar proteins

  - One dimer → next dimer → tube grows

  - Thirteen chains of tubulin doublets surround the central cavity of hte microtubule.

  - $$\ce{\alpha-tubulin + \beta-tubulin -> \alpha\beta doublet -> polymer of doublets (microtubule)}$$

  - the two ends of a microtubule are different: one is designated the "plus" end and the other the "minus" end.

  - Tubulin dimers can be rapidly added or subtracted, mainly at the plus end, lengthening or shortening the microtubule.

  - $$\text{Microtubules} \leftrightarrow \text{tubulin doublets}$$

  - The capacity to [change length rapidly]{.underline} makes microtubules dynamic structures: they are [readily adapted for new purposes]{.underline} in the cell.

  - e.g. by disassembly 分解 and reassembly 重组, they can drag along substances attached to them

  - In plants, microtubules act as a framework for the assembly of cellulose and help orient the cellulose fibers of the cell wall.

- motor proteins: specialized molecules that use cellular energy to change their shapes and move

  - bind to and move along the microtubules, carrying materials from one part of the cell to another

  - two main types of motor proteins:

    1.  **kinesins** 驱动蛋白: move materials toward the "plus" end
    2.  **dyneins** 动力蛋白: move materials toward the "minus" end

- microtubules and their associated proteins line the interior of **cilia** 纤毛 and **flagella** 鞭毛 on eukaryotic cells

  - many cells have one or the other of these appendages, which form from projections of the cell membrane

- **cilia**: $\pu{0.25\mu m}$ in length

  - They occur by the hundreds on individual cells and move stiffly to either [propel the cell]{.underline} (i.e. in protists 原生生物) or to [move fluid over a stationary cell]{.underline} (i.e. in the human respiratory system)

- **flagella**: longer, $\pu{100}$ to $\pu{200\mu m}$

  - occur [singly or in pairs]{.underline}

  - can [push or pull a cell]{.underline} through its [aqueous environment]{.underline}

- In cell biology, two approaches are often used to show that a structure or process A causes function B:

  1.  **Inhibition**: Use a drug thta inhibits A and see if B still occurs. If it does not, then A is probably a causative factor for B.
  2.  **Mutation**: Examine a cell that lacks the gene (or genes) for A and see if B still occurs. If it does not, then A is probably a causative factor for B.

## 5.4 Extracellular Materials Provide Structure

### The plant cell wall provides structure and protection

3 major roles of plant cell wall

1.  provides [support]{.underline} for the cell and plant by remaining [rigid]{.underline}
    - [flexible]{.underline} enough that it can allow the plant to bend in the wind
2.  acts as a [barrier]{.underline} to infection by [fungi and other organisms]{.underline} that can cause [plant diseases]{.underline}
3.  contributes to plant form by [growing as the plant cells expand]{.underline}

Cytoplasms of adjacent plant cells are connected by numerous cell membrane-lined channels called **plasmodesmata** (plasmodesma) 胞间连丝, about $\pu{20-40\mu m}$

### The extracellular matrix 细胞外基质 supports tissue functions in animals

Many animal cells are surrounded by, or in contact with an **extracellular matrix** 细胞外基质.

> 细胞外基质：由特定类型的细胞产生但不是细胞的部分：为细胞提供支持并常作为组织的共同成分之一，尤其是结缔组织。

This matrix is composed of three types of molecules:

1.  fibrous proteins such as **collagen** 胶原质
    - **collagen**: the most abundant protein in [mammals]{.underline}, constituting [over 25% of the protein]{.underline} in the [human body]{.underline}
2.  a matrix of glycoproteins 糖蛋白 termed **proteoglycans** 蛋白聚糖, consisting primarily of sugars
3.  a third group of proteins that [link the fibrous proteins and the gel-like proteoglycan matrix]{.underline} together

Several functions of extracellular matrix:

- [holds cells together]{.underline} in tissues

- contributes to the [physical properties of cellular aggregates]{.underline} called **tissue**s

  - **Cartilage** 软骨 and bone are part of connective tissue.

  - e.g. The mineral component of bone is laid down on an organized extracellular matix.

    - In tissue engineering, cells are removed from the extracellular matrix and the latter serves as a scaffold for the development of new organs with the correct architecture.

- helps filter materials passing between different tissues

  - e.g. especially important in the kidney

- helps orient cell movements during [embryonic development]{.underline} and during [tissue repair]{.underline}

- plays a role in [chemical signaling]{.underline} from one cell to another

  - Proteins connect the cell's cell membrane to the extracellular matrix.

  - These [proteins]{.underline} (e.g. **integrin** 整合蛋白) [span the cell membrane]{.underline} and are involved with [transmitting signals]{.underline} to the [interior of the cell]{.underline}.

  - This allows [communication]{.underline} between the [extracellular matrix]{.underline} and the [cytoplasm]{.underline} of the cell.

## 5.5 Eukaryotic Cells Evolved in Several Steps

The first life on Earth was prokaryotic.

- **Prokaryotes** are [simple cells without a nucleus]{.underline}, like bacteria.

For about [1 billion years]{.underline}, only prokaryotes existed on Earth.

This period started when prokaryotic cells first appeared.

It lasted until about 2.7 billion years ago.

At 2.7 billion years ago, the first evidence of eukaryotic cells appears in ancient rocks.

- **Eukaryotes** are [complex cells with a nucleus]{.underline} – the ancestors of plants and animals.

A single prokaryotic cell is often biochemically specialized, limited in the resources it can use and the functions it can perform.

### Internal membranes and the nuclear envelope probably came from the cell membrane

theory: the endomembrane system and the cell nucleus originated by related processes

A bacterium with enclosed compartments would have several [evolutionary advantages]{.underline}.

- Chemicals could be concentrated in particular regions of the cell, allowing chemical reactions to proceed more efficiently.
